server:
    port: 8082
spring:
  dubbo:
    application:
      name: service-consumer
    base-package: com.ngsky.web.api
    registry:
      address: 192.168.204.128
      port: 2181
    protocol:
      name: dubbo
      serialization: hessian2
    consumer:
      timeout: 1000
      check: true
      retries: 2