server:
    port: 8081
spring:
  dubbo:
    application:
      name: service-provider
    base-package: com.ngsky.service.impl
    registry:
      address: 192.168.42.157
      port: 2181
    protocol:
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0