server:
    port: 8081
spring:
  dubbo:
    application:
      name: service-provider
    base-package: com.ngsky.service.impl
    registry:
      address: 192.168.204.128
      port: 2181
    protocol:
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ngsky_shop?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
    username: root
    password: daxiong

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  scan-package: com.ngsky.mapper  # 注意：对应实体类的路径
